services:
  db:
    image: opengauss/opengauss-server:latest
    container_name: bank_opengauss
    restart: always
    privileged: true
    environment:
      # openGauss 默认管理员用户为 gaussdb
      GS_PASSWORD: Gauss@123
      GS_DB: bank_system
      GS_USERNAME: bank_admin
      OTHER_PG_CONF: |
        use_workload_manager = off
      TZ: Asia/Shanghai
    ports:
      # 端口映射：宿主机端口:容器内端口
      - "5432:5432"
    volumes:
      # 数据持久化：将容器内的数据映射到 Docker volume，防止容器销毁后数据丢失
      - opengauss_data:/var/lib/opengauss/data

volumes:
  # 声明数据卷
  opengauss_data:
